<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="BMOHANTY02" failures="2" tests="16" name="Test" time="12.439" errors="0" timestamp="2023-12-29T14:01:54 IST">
  <testcase classname="testCases.DataCompletenessValidation" name="dataCompleteness" time="5.545"/>
  <testcase classname="testCases.DataCompletenessValidation" name="dataCompleteness" time="0.088"/>
  <testcase classname="testCases.DataCompletenessValidation" name="dataCompleteness" time="4.055"/>
  <testcase classname="testCases.DataCompletenessValidation" name="dataCompleteness" time="0.087"/>
  <testcase classname="testCases.DataCompletenessValidation" name="dataCompleteness" time="0.043"/>
  <testcase classname="testCases.DataCompletenessValidation" name="dataCompleteness" time="0.01"/>
  <testcase classname="testCases.DataCompletenessValidation" name="dataCompleteness" time="0.008"/>
  <testcase classname="testCases.DataCompletenessValidation" name="dataCompleteness" time="0.015"/>
  <testcase classname="testCases.DataCompletenessValidation" name="dataCompleteness" time="0.011"/>
  <testcase classname="testCases.DataCompletenessValidation" name="dataCompleteness" time="0.014"/>
  <testcase classname="testCases.DataCompletenessValidation" name="dataCompleteness" time="0.049">
    <failure type="java.lang.AssertionError" message="Test failed: java.lang.AssertionError: Details of Differences:
Row 1:
   Column 2: List1 = EMP_NAME: Sunil, List2 = EMP_NAME: Smith
 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Test failed: java.lang.AssertionError: Details of Differences:
Row 1:
   Column 2: List1 = EMP_NAME: Sunil, List2 = EMP_NAME: Smith
 expected [true] but found [false]
at testCases.DataCompletenessValidation.dataCompleteness(DataCompletenessValidation.java:131)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
Caused by: java.util.concurrent.ExecutionException: java.lang.AssertionError: Details of Differences:
Row 1:
   Column 2: List1 = EMP_NAME: Sunil, List2 = EMP_NAME: Smith
 expected [true] but found [false]
at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
at testCases.DataCompletenessValidation.dataCompleteness(DataCompletenessValidation.java:128)
... 32 more
Caused by: java.lang.AssertionError: Details of Differences:
Row 1:
   Column 2: List1 = EMP_NAME: Sunil, List2 = EMP_NAME: Smith
 expected [true] but found [false]
at testCases.DataCompletenessValidation.lambda$dataCompleteness$2(DataCompletenessValidation.java:101)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- dataCompleteness -->
  <testcase classname="testCases.DataCompletenessValidation" name="dataCompleteness" time="0.012"/>
  <testcase classname="testCases.DataCompletenessValidation" name="dataCompleteness" time="0.012"/>
  <testcase classname="testCases.DataCompletenessValidation" name="dataCompleteness" time="0.011"/>
  <testcase classname="testCases.TableMetadataValidation" name="tableMetadataValidation" time="0.009">
    <failure type="java.lang.AssertionError" message="Test failed: [{COLUMN_NAME=EMP_ID345, TARGET_COLUMN_NAME=EMP_ID}, {COLUMN_NAME=T_EMP_ID1212, TARGET_COLUMN_NAME=T_EMP_ID}] expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Test failed: [{COLUMN_NAME=EMP_ID345, TARGET_COLUMN_NAME=EMP_ID}, {COLUMN_NAME=T_EMP_ID1212, TARGET_COLUMN_NAME=T_EMP_ID}] expected [true] but found [false]
at testCases.TableMetadataValidation.tableMetadataValidation(TableMetadataValidation.java:60)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
Caused by: java.lang.AssertionError: [{COLUMN_NAME=EMP_ID345, TARGET_COLUMN_NAME=EMP_ID}, {COLUMN_NAME=T_EMP_ID1212, TARGET_COLUMN_NAME=T_EMP_ID}] expected [true] but found [false]
at testCases.TableMetadataValidation.tableMetadataValidation(TableMetadataValidation.java:56)
... 32 more
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- tableMetadataValidation -->
  <testcase classname="testCases.TableMetadataValidation" name="tableMetadataValidation" time="0.005"/>
</testsuite> <!-- Test -->
